<?xml version="1.0" encoding="utf-8"?><Database Name="login" Class="RegisterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.register1" Member="register1s">
    <Type Name="register1">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>